name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main

      - name: Install Azure CLI & ML extension
        run: |
          az extension add -n ml -y

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set environment variables
        run: |
          echo "RESOURCE_GROUP=rg-dp100-labs" >> $GITHUB_ENV
          echo "WORKSPACE_NAME=mlw-dp100-labs_2" >> $GITHUB_ENV

      - name: Submit Azure ML Job
        run: |
          az ml job create --file src/job.yml \
            --resource-group $RESOURCE_GROUP \
            --workspace-name $WORKSPACE_NAME
